/**
 * Token generator — single source of truth is `src/shared/styles/tokens.ts`.
 *
 * Emits:
 *  - src/shared/styles/colors.css        (global override: :root / [data-theme] / prefers-color-scheme)
 *  - src/shared/styles/tokens.module.css  (self-contained `.tokens` layer components `composes`)
 *
 * Run with `npm run gen-tokens`. Do not hand-edit the generated .css files.
 */
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { primitives, semantics } from "../src/shared/styles/tokens.ts";

const HERE = fileURLToPath(new URL(".", import.meta.url));
const STYLES_DIR = resolve(HERE, "../src/shared/styles");

const BANNER =
	"/* GENERATED by scripts/gen-tokens.ts — do not edit by hand. */\n";

const primitiveDecls = (indent: string) =>
	Object.entries(primitives)
		.map(([name, value]) => `${indent}--sk-${name}: ${value};`)
		.join("\n");

const semanticDecls = (indent: string, theme: "light" | "dark") =>
	Object.entries(semantics)
		.map(([name, values]) => `${indent}--sk-${name}: ${values[theme]};`)
		.join("\n");

/* ---- colors.css (global override) ---- */
const colorsCss = `${BANNER}
:root {
${primitiveDecls("\t")}
}

/* Semantic theme variables — light theme defaults */
:root {
${semanticDecls("\t", "light")}
}

/* OS dark mode preference (when no explicit data-theme is set) */
@media (prefers-color-scheme: dark) {
	:root:not([data-theme]) {
${semanticDecls("\t\t", "dark")}
	}
}

/* Explicit dark theme override */
[data-theme="dark"] {
${semanticDecls("\t", "dark")}
}

/* Explicit light theme override */
[data-theme="light"] {
${semanticDecls("\t", "light")}
}
`;

/* ---- tokens.module.css (self-contained layer for components to compose) ---- */
const tokensModuleCss = `${BANNER}
/*
 * Self-contained token layer. A component that \`composes: tokens from "..."\` gets every
 * --sk-* variable with baked-in light + dark values, so it is correctly themed with NO
 * global stylesheet import. When \`summit-kit/styles\` IS imported (or a consumer sets an
 * --sk-* var on an ancestor), that value wins over these defaults.
 */
.tokens {
${primitiveDecls("\t")}

${semanticDecls("\t", "light")}
}

/* OS dark preference when no explicit theme is chosen */
@media (prefers-color-scheme: dark) {
	:where(:root:not([data-theme])) .tokens {
${semanticDecls("\t\t", "dark")}
	}
}

/* Explicit theme overrides on any ancestor */
:where([data-theme="dark"]) .tokens {
${semanticDecls("\t", "dark")}
}

:where([data-theme="light"]) .tokens {
${semanticDecls("\t", "light")}
}
`;

writeFileSync(resolve(STYLES_DIR, "colors.css"), colorsCss);
writeFileSync(resolve(STYLES_DIR, "tokens.module.css"), tokensModuleCss);

console.log("Generated colors.css and tokens.module.css from tokens.ts");
